// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package server

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ReportingRequestAggregation.
const (
	Daily   ReportingRequestAggregation = "daily"
	Monthly ReportingRequestAggregation = "monthly"
	Weekly  ReportingRequestAggregation = "weekly"
)

// Valid indicates whether the value is a known member of the ReportingRequestAggregation enum.
func (e ReportingRequestAggregation) Valid() bool {
	switch e {
	case Daily:
		return true
	case Monthly:
		return true
	case Weekly:
		return true
	default:
		return false
	}
}

// ChartData defines model for ChartData.
type ChartData struct {
	Contracted int                `json:"contracted"`
	Csp        *string            `json:"csp,omitempty"`
	Date       openapi_types.Date `json:"date"`
	Delivered  int                `json:"delivered"`
	GpuType    *string            `json:"gpu_type,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message *string `json:"message,omitempty"`
}

// ReportingRequest defines model for ReportingRequest.
type ReportingRequest struct {
	Aggregation ReportingRequestAggregation `json:"aggregation"`
	Csp         *[]string                   `json:"csp,omitempty"`
	EndDate     openapi_types.Date          `json:"end_date"`
	GpuType     *[]string                   `json:"gpu_type,omitempty"`
	StartDate   openapi_types.Date          `json:"start_date"`
}

// ReportingRequestAggregation defines model for ReportingRequest.Aggregation.
type ReportingRequestAggregation string

// ReportingResponse defines model for ReportingResponse.
type ReportingResponse struct {
	Chart *[]ChartData `json:"chart,omitempty"`
	Table *TableData   `json:"table,omitempty"`
}

// TableData defines model for TableData.
type TableData struct {
	Rows *[]TableRow `json:"rows,omitempty"`
}

// TableRow defines model for TableRow.
type TableRow struct {
	Category *string         `json:"category,omitempty"`
	Data     *map[string]int `json:"data,omitempty"`
}

// PostReportingJSONRequestBody defines body for PostReporting for application/json ContentType.
type PostReportingJSONRequestBody = ReportingRequest
